hmrc/pbik-frontend

- app/controllers/ExclusionListController.scala
Added explicit logging for optimistic locks.
We can now search for
"Exclusion search matched" which shows the optlock for the searched employee
"Committing Exclusion" which shows the optlock when committing
> Additional logging in Exclusion controller for optimistic locks

- app/views/exclusion/whatNextExclusion.scala.html
- app/views/exclusion/whatNextRescind.scala.html
- app/views/parentTemplate.scala.html
- app/views/registration/whatNextAddRemove.scala.html
- public/assets/javascript/print.js
Added print button on the registration and exclusion confirmation screens. Purloined some code to exclude from mobiles and also don't show if javascript is disabled.
> Print button pull request

- app/config/AppConfig.scala
- app/utils/SplunkLogger.scala
- app/views/exclusion/exclusionOverview.scala.html
- conf/application.conf
- conf/messages
- conf/messages.cy
Added configuration, content  and code to support product owners request to limit exclusions to 300 employees
> Limit exclusions to 300 employees

- project/build.properties
DDCNLS-1386: upgraded sbt version to 0.13.15
> DDCNLS-1386: upgraded sbt version to 0.13.15

- conf/messages
- conf/messages.cy
- test/controllers/QuestionnaireControllerSpec.scala
- test/controllers/auth/AuthControllerSpec.scala
@nehakannaujia - I've updated contractions and smart quotes, some capitalisation and some blatantly dodgy messaging. 
It broke 3 tests, but they have now been updated.
> DDCNLS-1514: Review and update content style (unit tests updated)

- project/FrontendBuild.scala
- test/controllers/HomePageControllerTest.scala
DDCNLS-3046:Bootstrap library upgrade
> DDCNLS-3046:Bootstrap library upgrade

- app/connectors/ContactFrontendConnector.scala
- app/controllers/ExclusionListController.scala
- app/controllers/HelpAndContactController.scala
- app/controllers/HomePageController.scala
- app/controllers/actions/AuthAction.scala
- app/controllers/actions/NoSessionCheckAction.scala
- app/utils/ControllersReferenceData.scala
- build.sbt
- project/AppDependencies.scala
- project/plugins.sbt
Updated logging: added logs in bad paths. Updated log levels.
> [RS][DDCE-673] Updating & correcting logging.

- app/assets/stylesheets/pbik.scss
Resolved "Elements must have sufficient color contrast" 
No impact to any other repos
We will be able to fix 1 issue out for 4 mentioned by aXe tool. I have finding document ready for that.
Link to Confluence page > https://confluence.tools.tax.service.gov.uk/pages/viewpage.action?pageId=202082383
> DDCE-810 Resolved Elements must have sufficient color contrast

- .github/PULL_REQUEST_TEMPLATE.md
- app/views/Overview.scala.html
- app/views/exclusion/ExclusionOverview.scala.html
- app/views/exclusion/RemovalConfirmation.scala.html
- app/views/exclusion/SearchResults.scala.html
- app/views/registration/ConfirmUpdateNextTaxYear.scala.html
- app/views/registration/NextTaxYear.scala.html
- app/views/registration/WhatNextAddRemove.scala.html
- conf/app.routes
Fixed the "\<dl\> elements must only directly contain properly-ordered" issue by converting them to \<ol\> tags with \<li\> children. Performed a manual check on each affected page to confirm that the change resolved the issue without affecting the look of the page
No acceptance or unit tests required updates
No dependency updates to do as they have recently been updated by other stories
- Were there …
> DDCE-813: Fixed the "<dl> elements must only directly contain properly-ordered" issue

- app/views/MainTemplate.scala.html
- app/views/helpers/FullWidthBanner.scala.html
Resolve "All page content must be contained by landmarks" issue with PBIK
> DDCE-811 Resolved All page content must be contained by landmarks

- app/views/ErrorTemplate.scala.html
- conf/application.conf
- project/AppDependencies.scala
Implemented PBIK accessibility statement using the accessibility-statement-frontend microservice.
> DDCE-1084: Added code to implement accessibility statement microservice

- app/controllers/AuthController.scala
- app/utils/ControllersReferenceData.scala
- test/controllers/AuthControllerSpec.scala
- test/controllers/ExclusionListControllerSpec.scala
- test/utils/ControllersReferenceDataSpec.scala
Updated some status codes to better reflect what is happening in the service for monitoring purposes.
> [DP][DDCE-896]: Update some status codes returned

- app/config/AppConfig.scala
- app/controllers/ExternalUrls.scala
- app/controllers/actions/AuthAction.scala
- conf/application.conf
- project/AppDependencies.scala
- project/plugins.sbt
- test/connectors/TierConnectorSpec.scala
- test/controllers/LanguageSupportSpec.scala
- test/controllers/ManageRegistrationControllerSpec.scala
- test/controllers/WhatNextPageControllerSpec.scala
- test/support/MockExclusionListController.scala
> DDCE-1297: Removed deprecated CA_FRONTEND

- app/config/AppConfig.scala
- app/views/MainTemplate.scala.html
- conf/application.conf
- test/support/TestCYEnabledConfig.scala
> DDCE-1077: Added Google tag manager

- app/utils/TaxDateUtils.scala
- build.sbt
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
- test/utils/TaxDateUtilsSpec.scala
Updated Scala from 2.11.x to 2.12.12 and subsequently updated to the latest sbt version (1.3.13) and the associated sbt plugins.
> [EH][DDCE-1279] Upgraded sbt and scala versions

- app/controllers/HomePageController.scala
- app/controllers/RedirectController.scala
- app/controllers/actions/AuthAction.scala
- app/controllers/actions/NoSessionCheckAction.scala
- app/controllers/registration/ManageRegistrationController.scala
- app/views/GovukLayoutWrapper.scala.html
- app/views/SignedOut.scala.html
- app/views/registration/ConfirmAddCurrentTaxYear.scala.html
- app/views/registration/ConfirmUpdateNextTaxYear.scala.html
- app/views/registration/CurrentTaxYear.scala.html
- app/views/registration/NextTaxYear.scala.html
- app/views/registration/RemoveBenefitNextTaxYear.scala.html
- build.sbt
- conf/messages
- conf/messages.cy
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
- test/controllers/SignedOutControllerSpec.scala
- test/controllers/actions/AuthActionSpec.scala
- test/controllers/actions/MinimalAuthActionSpec.scala
- test/services/BikListServiceSpec.scala
- test/services/EilListServiceSpec.scala
- test/services/RegistrationServiceSpec.scala
- test/services/SessionServiceSpec.scala
- test/utils/DateUtilsSpec.scala
- test/utils/SplunkLoggerSpec.scala
- test/utils/SystemPropertiesHelperSpec.scala
- test/utils/TaxDateUtilsSpec.scala
- test/utils/URIValuesSpec.scala
> bootstrap play upgrade and fixed failing tests

- conf/application-json-logger.xml
- conf/logback.xml
> DDCE-2154 - implemented correct logging settings for pbik frontend

- .github/PULL_REQUEST_TEMPLATE.md
- build.sbt
- project/AppDependencies.scala
- run_all_tests.sh
> DDCE-2346:Play-frontend-hmrc upgrade

- conf/messages
- conf/messages.cy
> DDCE-2346fix:Address new reverse tabnabbing alert

- conf/app.routes
- conf/messages
- conf/messages.cy
- project/AppDependencies.scala
> DDCE-2346_fix:Reverse Tabnabbing fix update

- app/controllers/registration/ManageRegistrationController.scala
- app/views/registration/ConfirmAddCurrentTaxYear.scala.html
- app/views/registration/ConfirmUpdateNextTaxYear.scala.html
- conf/messages
- conf/messages.cy
- project/AppDependencies.scala
- project/plugins.sbt
- test/controllers/ManageRegistrationControllerSpec.scala
- test/views/ConfirmNextYearViewSpec.scala
> DDCE-1746 content changes and tests fix

- conf/app.routes
- test/controllers/ManageRegistrationControllerSpec.scala
- test/views/ConfirmNextYearViewSpec.scala
> DDCE-1746 PBIK Improvement url update and test fix

- conf/messages.cy
> DDCE-1599 fixed welsh message

- conf/application.conf
- test/controllers/SignedOutControllerSpec.scala
> DDCE-2251: Fixing ZAP Warning alert

- app/views/exclusion/WhatNextExclusion.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- test/controllers/ExclusionListControllerSpec.scala
- test/views/WhatNextExclusionViewSpec.scala
> DDCE-1608: PBIK: Improvements to 'Exclusion complete' confirmation page

- .gitignore
- app/controllers/StartPageController.scala
- app/views/GovukLayoutWrapper.scala.html
- app/views/StartPage.scala.html
- app/views/Summary.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages
- conf/messages.cy
- project/AppDependencies.scala
- test/controllers/ExclusionListControllerSpec.scala
- test/controllers/HomePageControllerSpec.scala
- test/controllers/StartPageControllerSpec.scala
- test/controllers/actions/AuthActionSpec.scala
- test/controllers/actions/MinimalAuthActionSpec.scala
- test/controllers/actions/NoSessionCheckActionSpec.scala
- test/views/StartPageViewSpec.scala
- test/views/SummaryViewSpec.scala
- test/views/WhatNextAddRemoveViewSpec.scala
- test/views/WhatNextExclusionViewSpec.scala
- test/views/helper/JsoupMatchers.scala
> [DDCE-1598]:PBIK: Implement new Start Page and changes to Summary Page

- app/controllers/WhatNextPageController.scala
- app/controllers/registration/ManageRegistrationController.scala
- app/views/registration/RemoveBenefitConfirmationNextTaxYear.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- test/controllers/ManageRegistrationControllerSpec.scala
- test/controllers/WhatNextPageControllerSpec.scala
> DDCE-1613:Changes to remove benefit or expense page

- app/views/registration/RemoveBenefitNextTaxYear.scala.html
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
> DDCE-2654: Non-descriptive legend text & Sbt update

- app/controllers/ExclusionListController.scala
- app/controllers/registration/ManageRegistrationController.scala
- build.sbt
- project/AppDependencies.scala
- project/plugins.sbt
- test/controllers/ManageRegistrationControllerSpec.scala
> DDCE-3082: bootstrap upgrade

- README.md
> DDCE-RemoveBadge : Remove the broken build badge from readme

- app/assets/stylesheets/application.scss
- app/views/exclusion/SearchResults.scala.html
- app/views/registration/AddBenefitConfirmationNextTaxYear.scala.html
- app/views/registration/ConfirmAddCurrentTaxYear.scala.html
- app/views/registration/ConfirmUpdateNextTaxYear.scala.html
Remaining VNU accessibility errors fixed.
[reportPbik_accessibility-assessment-report](https://user-images.githubusercontent.com/87376121/203543601-ca00a9f2-c264-4680-94bc-c34f81aa95dd.png)
Requires:
[pbik-acceptance-tests PR](https://github.com/hmrc/pbik-acceptance-tests/pull/63)
[Add to Pipeline PR](https://github.com/hmrc/build-jobs/pull/12077)
> DDCE-3416: Accessibility fixes

- README.md
- app/utils/ControllersReferenceData.scala
- app/views/ErrorPage.scala.html
- app/views/GovukLayoutWrapper.scala.html
- app/views/registration/ConfirmUpdateNextTaxYear.scala.html
- app/views/registration/RemoveBenefitNextTaxYear.scala.html
- app/views/registration/RemoveBenefitOtherReason.scala.html
- build.sbt
- conf/application.conf
- conf/messages
- conf/messages.cy
- project/AppDependencies.scala
- public/assets/javascript/pbik.js
- public/assets/javascript/print.js
- test/connectors/TierConnectorSpec.scala
ensure the PBIK service is protected against cross-site scripting attacks (XSS)
> DDCE-3737: CSP filtering on PBIK

- README.md
- conf/application.conf
- project/AppDependencies.scala
- project/plugins.sbt
Upgrade service manager from sm to sm2
> DDCE-4518: Upgrade service manager to sm2

- README.md
- app/controllers/ExclusionListController.scala
- app/models/PbikError.scala
- app/utils/ControllersReferenceData.scala
- app/views/GovukLayoutWrapper.scala.html
- app/views/registration/ConfirmAddCurrentTaxYear.scala.html
- app/views/registration/RemoveBenefitOtherReason.scala.html
- build.sbt
- run_all_tests.sh
- test/views/ConfirmNextYearViewSpec.scala
- test/views/ExclusionNinoOrNoNinoViewSpec.scala
- test/views/ExclusionOverviewViewSpec.scala
- test/views/MaintenancePageViewSpec.scala
- test/views/NextYearViewSpec.scala
- test/views/NinoExclusionSearchViewSpec.scala
- test/views/NoNinoExclusionSearchViewSpec.scala
- test/views/SearchResultViewSpec.scala
- test/views/SignedOutViewSpec.scala
- test/views/StartPageViewSpec.scala
- test/views/SummaryViewSpec.scala
- test/views/WhatNextAddRemoveViewSpec.scala
- test/views/WhatNextExclusionViewSpec.scala
- test/views/helper/PBIKViewSpec.scala
- test/views/templatemodels/CheckboxIdSpec.scala
- test/views/templatemodels/PageTitleSpec.scala
> DDCE-4359 Fix a11y issues

- app/utils/FormMappings.scala
- project/AppDependencies.scala
DDCE-6117:Update Error Message on PBIK FE: Search for the employee to exclude
> DDCE-6117:Update Error Message on PBIK FE: Search for the employee to exclude

- project/AppDependencies.scala
- project/plugins.sbt
Updated bootstrap higher due to vulnerability violation
> DDCE_ 6117a  Updated bootstrap higher due to vulnerability violation
